name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"     
  workflow_dispatch:         

permissions:
  contents: write       

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""                     # você pode deixar vazio se quiser só o plugin isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
